mf_id = "__testing_letter_99999.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 01.11.1932"

[mf_data]
"letter_99999_001" = "https://www.monacensia-digital.de/i3f/v20/415543/info.json"
"letter_99999_002" = "https://www.monacensia-digital.de/i3f/v20/415544/info.json"
